/**
 * AuthService.js
 * Auth Service cutover wrapping real Supabase Auth.
 * Completely eliminates local password storage, fake JWTs, and local user arrays.
 */

import { supabase } from './SupabaseClient.js';
import { globalEntitlements } from './EntitlementService.js';
import { ScopedStorageService } from './ScopedStorageService.js';

async function requestAuthEmailApi(path, body) {
  const response = await fetch(path, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body)
  });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) {
    const error = new Error(payload.error || 'Authentication email request failed.');
    error.code = payload.code || (response.status === 429 ? 'over_email_send_rate_limit' : 'email_delivery');
    throw error;
  }
  return payload;
}

export async function signUpUser(email, password, displayName = '') {
  const payload = await requestAuthEmailApi('/api/auth/signup', {
    email: email.trim(),
    password,
    displayName
  });
  return {
    user: payload.user || null,
    session: null,
    emailSent: payload.emailSent !== false,
    otpLength: payload.otpLength || null,
    verificationType: payload.verificationType || 'signup'
  };
}

export async function loginUser(email, password) {
  const { data, error } = await supabase.auth.signInWithPassword({
    email: email.trim(),
    password: password
  });

  if (error) throw error;
  return data;
}

export async function logoutUser() {
  const { error } = await supabase.auth.signOut();
  if (error) console.warn('Supabase logout warning:', error.message);

  // Clear memory cache and user storage
  try {
    ScopedStorageService.wipeAllUserCaches();
  } catch (e) {}
}

export async function getAuthSession() {
  const { data, error } = await supabase.auth.getSession();
  if (error || !data?.session) {
    return null;
  }

  const session = data.session;
  // If access token is expired or expires within 10 seconds, attempt legitimate refresh
  const now = Math.floor(Date.now() / 1000);
  if (session.expires_at && session.expires_at <= now + 10) {
    const { data: refreshed, error: refreshErr } = await supabase.auth.refreshSession().catch(() => ({ data: null, error: true }));
    if (refreshErr || !refreshed?.session) {
      await logoutUser();
      return null;
    }
    return refreshed.session;
  }

  return session;
}

export const getSession = getAuthSession;
export const signUp = signUpUser;
export const signIn = loginUser;
export const login = loginUser;
export const logout = logoutUser;
export const signOut = logoutUser;

export async function getCurrentAuthUser() {
  const session = await getAuthSession();
  return session?.user || null;
}

export function subscribeToAuthStateChange(callback) {
  return supabase.auth.onAuthStateChange((event, session) => {
    if (event === 'SIGNED_OUT') {
      try { sessionStorage.clear(); } catch (e) {}
    } else if (event === 'SIGNED_IN' && session?.user) {
      try { sessionStorage.setItem('supabase_user_cache', JSON.stringify(session.user)); } catch (e) {}
    }
    callback(event, session);
  });
}
export const onAuthStateChange = subscribeToAuthStateChange;
export const resetPassword = requestPasswordReset;
export const updatePassword = updateUserPassword;

export async function requestPasswordReset(email) {
  const { data, error } = await supabase.auth.resetPasswordForEmail(email.trim(), {
    redirectTo: `${window.location.origin}/reset-password`
  });
  if (error) throw error;
  return data;
}

export async function verifyEmailOtp(email, token) {
  if (!email || !token) throw new Error('Email and verification code are required.');

  // Codes generated by the custom Brevo API can be either signup (first
  // message) or magiclink (resend). Supabase also accepts the generic email
  // type for newer projects, so keep all compatible variants here.
  let result = { data: null, error: null };
  for (const type of ['signup', 'magiclink', 'email']) {
    result = await supabase.auth.verifyOtp({
      email: email.trim(),
      token: token.trim(),
      type
    });
    if (!result.error) break;
  }

  if (result.error) throw result.error;

  if (result.data?.session?.user) {
    try {
      sessionStorage.setItem('supabase_user_cache', JSON.stringify(result.data.session.user));
    } catch (e) {}
  }

  return result.data;
}

export async function resendEmailOtp(email, userId = '') {
  if (!email || !email.includes('@')) throw new Error('Valid email address required.');
  return requestAuthEmailApi('/api/auth/resend', {
    email: email.trim(),
    userId: userId || undefined
  });
}

/** Check whether an email already has an account. Used only to give clear,
 * actionable sign-in and password-reset feedback in the auth UI. */
export async function checkEmailRegistered(email) {
  if (!email || !email.includes('@')) throw new Error('Valid email address required.');
  return requestAuthEmailApi('/api/auth/check-email', { email: email.trim() });
}

export function isEmailVerified(user) {
  if (!user) return false;
  return Boolean(user.email_confirmed_at || user.confirmed_at || user.user_metadata?.email_verified);
}

export async function updateUserPassword(newPassword) {
  const { data, error } = await supabase.auth.updateUser({
    password: newPassword
  });
  if (error) throw error;
  return data;
}

// Session-backed helper wrappers
export function getCurrentUser() {
  try {
    const sessionUser = JSON.parse(sessionStorage.getItem('supabase_user_cache') || 'null');
    if (!sessionUser) return null;
    const metadata = sessionUser.user_metadata || {};
    return {
      ...sessionUser,
      name: sessionUser.name || metadata.full_name || metadata.name || sessionUser.email?.split('@')[0] || 'User'
    };
  } catch (e) {
    return null;
  }
}

export function isLoggedIn() {
  try {
    return Boolean(sessionStorage.getItem('supabase_user_cache'));
  } catch (e) {
    return false;
  }
}

export function isPro() {
  return globalEntitlements.getPlanId() === 'pro' || globalEntitlements.getEffectivePlanId() === 'premium' || globalEntitlements.getEffectivePlanId() === 'premium_group';
}

export function isPaidPlan() {
  return globalEntitlements.getEffectivePlanId() !== 'free';
}

async function groupRequest(options = {}) {
  const session = await getAuthSession();
  if (!session?.access_token) throw new Error('Please sign in first.');
  const response = await fetch('/api/groups/manage', {
    ...options,
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${session.access_token}`,
      ...(options.headers || {})
    }
  });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(payload.error || 'Group request failed.');
  return payload;
}

export function getGroupManagement() {
  return groupRequest({ method: 'GET' });
}

export function inviteGroupMember(memberEmail) {
  return groupRequest({
    method: 'POST',
    body: JSON.stringify({ subAction: 'invite_member', memberEmail })
  });
}

export function acceptGroupInvitation(groupId) {
  return groupRequest({
    method: 'POST',
    body: JSON.stringify({ subAction: 'accept_invitation', groupId })
  });
}

export function declineGroupInvitation(groupId) {
  return groupRequest({
    method: 'POST',
    body: JSON.stringify({ subAction: 'decline_invitation', groupId })
  });
}

export function removeGroupMember(groupId, memberId) {
  return groupRequest({
    method: 'POST',
    body: JSON.stringify({ subAction: 'remove_member', groupId, memberId })
  });
}

export function getCurrentPlanId() {
  return globalEntitlements.getEffectivePlanId();
}

export function upgradeToPro() {}
export async function redeemPromoCode(code) {
  if (!code) return { success: false, error: 'Promo code is required.' };
  try {
    const { data: { session } } = await supabase.auth.getSession();
    if (!session?.access_token) return { success: false, error: 'Please sign in first.' };
    const response = await fetch('/api/promo/validate', {
      method: 'POST',
      headers: { Authorization: 'Bearer ' + session.access_token, 'Content-Type': 'application/json' },
      body: JSON.stringify({ code })
    });
    const result = await response.json().catch(() => ({}));
    if (result.valid) {
      return { success: true, discount: result.discount };
    }
    return { success: false, error: result.reason || 'Promo code is not valid.' };
  } catch (e) {
    return { success: false, error: 'Promo validation failed. Please try again.' };
  }
}

async function adminRequest(path, options = {}) {
  const session = await getAuthSession();
  if (!session?.access_token) throw new Error('Please sign in first.');
  const response = await fetch(path, {
    ...options,
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${session.access_token}`,
      ...(options.headers || {})
    }
  });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(payload.error || 'Admin request failed.');
  return payload;
}

export async function isAdmin() {
  try {
    const result = await adminRequest('/api/admin?action=me');
    return result.isAdmin === true;
  } catch (_) {
    return false;
  }
}

export function adminGetOverview() {
  return adminRequest('/api/admin?action=overview');
}

export function adminGetUsers() {
  return adminRequest('/api/admin?action=users');
}

export function adminGetPortfolios() {
  return adminRequest('/api/admin?action=portfolios');
}

export function adminGetGroups() {
  return adminRequest('/api/admin?action=groups');
}

export function adminGetPromos() {
  return adminRequest('/api/admin?action=promos');
}

export function adminGetAuditLog(limit = 100) {
  return adminRequest(`/api/admin?action=audit-log&limit=${limit}`);
}

export function adminGetSystemInfo() {
  return adminRequest('/api/admin?action=system');
}

export function adminGetCareerSettings() {
  return adminRequest('/api/admin?action=career-settings');
}

export function adminGetCareerSettingsAudit(limit = 50) {
  return adminRequest(`/api/admin?action=career-settings-audit&limit=${limit}`);
}

export function adminUpdateCareerSettings({ templateId, enabled, freeExportLimit }) {
  return adminRequest('/api/admin?action=career-settings-update', {
    method: 'POST',
    body: JSON.stringify({ templateId, enabled, freeExportLimit })
  });
}

export function adminOverrideUserPlan({ userId, targetPlanId, status = 'active', durationDays = 30, startDate = null, endDate = null, groupSeats = 2, expiryDate = null, reason }) {
  return adminRequest('/api/admin?action=user-plan-override', {
    method: 'POST',
    body: JSON.stringify({ userId, targetPlanId, status, durationDays, startDate, endDate, groupSeats, expiryDate, reason })
  });
}

export function adminOverridePortfolioHosting({ portfolioId, hostingAction, reason }) {
  return adminRequest('/api/admin?action=portfolio-hosting-override', {
    method: 'POST',
    body: JSON.stringify({ portfolioId, hostingAction, reason })
  });
}

export function adminOverrideGroupSeats({ groupId, seatLimit, reason }) {
  return adminRequest('/api/admin?action=group-seat-override', {
    method: 'POST',
    body: JSON.stringify({ groupId, seatLimit, reason })
  });
}

export function adminCreatePromo(promoData) {
  return adminRequest('/api/admin?action=create-promo', {
    method: 'POST',
    body: JSON.stringify(promoData)
  });
}

export function adminDisablePromo({ promoId, reason }) {
  return adminRequest('/api/admin?action=disable-promo', {
    method: 'POST',
    body: JSON.stringify({ promoId, reason })
  });
}

export function adminOverrideUserLegacy({ userId, isLegacy, reason }) {
  return adminRequest('/api/admin?action=user-legacy-override', {
    method: 'POST',
    body: JSON.stringify({ userId, isLegacy, reason })
  });
}

export function adminGetPaymentRequests(status = 'all') {
  return adminRequest(`/api/admin?action=payment-requests&status=${status}`);
}

export function adminReviewPayment({ requestId, decision, reason }) {
  return adminRequest('/api/admin?action=review-payment', {
    method: 'POST',
    body: JSON.stringify({ requestId, decision, reason })
  });
}

export async function submitManualPayment(payload) {
  const session = await getAuthSession();
  if (!session?.access_token) throw new Error('Authentication required');

  const res = await fetch('/api/billing?action=submit-manual-payment', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${session.access_token}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(payload)
  });

  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(data.error || 'Payment submission failed');
  return data;
}

export async function getUserPaymentStatus() {
  const session = await getAuthSession();
  if (!session?.access_token) return { requests: [] };

  const res = await fetch('/api/billing?action=get-payment-status', {
    headers: {
      'Authorization': `Bearer ${session.access_token}`
    }
  });

  const data = await res.json().catch(() => ({ requests: [] }));
  return data;
}

export async function getPublicPaymentConfig() {
  try {
    const res = await fetch('/api/billing?action=payment-config');
    const data = await res.json().catch(() => ({ configured: false }));
    return data || { configured: false };
  } catch (_) {
    return { configured: false };
  }
}

// Backward-compat alias for legacy tests
export function adminSetUserPlan(userId, planId) {
  return adminOverrideUserPlan({ userId, targetPlanId: planId, reason: 'Legacy direct plan set' });
}
