-- Career Studio PR-4: local-only template availability and usage limits.
-- This table contains configuration metadata only; it never stores CV content.

CREATE TABLE IF NOT EXISTS public.cv_template_settings (
  template_id TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  free_export_limit INTEGER NOT NULL DEFAULT 2 CHECK (free_export_limit >= 0 AND free_export_limit <= 100),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

INSERT INTO public.cv_template_settings (template_id, display_name, enabled, free_export_limit)
VALUES ('ats-basic', 'ATS Basic', TRUE, 2)
ON CONFLICT (template_id) DO NOTHING;

ALTER TABLE public.cv_template_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "No direct client access to CV template settings" ON public.cv_template_settings;

CREATE TABLE IF NOT EXISTS public.career_studio_admin_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  action TEXT NOT NULL CHECK (action IN ('template_setting_updated')),
  template_id TEXT NOT NULL REFERENCES public.cv_template_settings(template_id) ON DELETE RESTRICT,
  limit_value INTEGER CHECK (limit_value >= 0 AND limit_value <= 100),
  result TEXT NOT NULL CHECK (result IN ('success', 'failure')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_career_studio_admin_audit_created
  ON public.career_studio_admin_audit_log(created_at DESC);

ALTER TABLE public.career_studio_admin_audit_log ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "No direct client access to Career Studio admin audit" ON public.career_studio_admin_audit_log;

REVOKE ALL ON public.cv_template_settings FROM anon, authenticated;
REVOKE ALL ON public.career_studio_admin_audit_log FROM anon, authenticated;
GRANT SELECT, UPDATE ON public.cv_template_settings TO service_role;
GRANT SELECT, INSERT, DELETE ON public.career_studio_admin_audit_log TO service_role;

CREATE OR REPLACE FUNCTION public.admin_update_cv_template_setting(
  p_template_id TEXT,
  p_enabled BOOLEAN,
  p_free_export_limit INTEGER,
  p_admin_user_id UUID
)
RETURNS public.cv_template_settings
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  updated_row public.cv_template_settings;
BEGIN
  IF p_template_id <> 'ats-basic' OR p_free_export_limit IS NULL OR p_free_export_limit < 0 OR p_free_export_limit > 100 THEN
    RAISE EXCEPTION 'Unsupported Career Studio setting';
  END IF;

  UPDATE public.cv_template_settings
  SET enabled = p_enabled,
      free_export_limit = p_free_export_limit,
      updated_at = NOW(),
      updated_by = p_admin_user_id
  WHERE template_id = p_template_id
  RETURNING * INTO updated_row;

  IF updated_row IS NULL THEN
    RAISE EXCEPTION 'Career Studio template setting not found';
  END IF;

  INSERT INTO public.career_studio_admin_audit_log
    (admin_user_id, action, template_id, limit_value, result)
  VALUES
    (p_admin_user_id, 'template_setting_updated', p_template_id, p_free_export_limit, 'success');

  RETURN updated_row;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_update_cv_template_setting(TEXT, BOOLEAN, INTEGER, UUID) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.admin_update_cv_template_setting(TEXT, BOOLEAN, INTEGER, UUID) TO service_role;
