-- Career Studio server/database-enforced rollout gate.
-- Additive only: legacy Portfolio tables and policies are not changed.

CREATE TABLE IF NOT EXISTS public.career_studio_rollout_config (
  id BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (id = TRUE),
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

INSERT INTO public.career_studio_rollout_config (id, enabled)
VALUES (TRUE, FALSE)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.career_studio_rollout_users (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  enabled_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_career_studio_rollout_users_enabled
  ON public.career_studio_rollout_users(enabled, created_at DESC);

CREATE TABLE IF NOT EXISTS public.career_studio_rollout_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  target_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  action TEXT NOT NULL CHECK (action IN ('rollout_user_updated', 'master_switch_updated')),
  enabled BOOLEAN,
  result TEXT NOT NULL CHECK (result IN ('success', 'failure')),
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_career_studio_rollout_audit_created
  ON public.career_studio_rollout_audit_log(created_at DESC);

ALTER TABLE public.career_studio_rollout_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.career_studio_rollout_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.career_studio_rollout_audit_log ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.career_studio_rollout_config FROM anon, authenticated;
REVOKE ALL ON public.career_studio_rollout_users FROM anon, authenticated;
REVOKE ALL ON public.career_studio_rollout_audit_log FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.career_studio_rollout_config TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.career_studio_rollout_users TO service_role;
GRANT SELECT, INSERT ON public.career_studio_rollout_audit_log TO service_role;

-- This is the only function exposed to authenticated/anonymous callers. It
-- returns a boolean and requires the caller to be the requested owner, so it
-- cannot disclose rollout state for another account.
CREATE OR REPLACE FUNCTION public.career_studio_access_allowed(p_user_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT auth.uid() = p_user_id
    AND COALESCE((SELECT enabled FROM public.career_studio_rollout_config WHERE id = TRUE), FALSE)
    AND EXISTS (
      SELECT 1 FROM public.career_studio_rollout_users
      WHERE user_id = p_user_id AND enabled = TRUE
    );
$$;

-- Serverless functions use this private variant with their service-role
-- client after validating the bearer token. It is not callable by browser
-- roles and does not expose the allowlist table.
CREATE OR REPLACE FUNCTION public.career_studio_service_access_allowed(p_user_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT p_user_id IS NOT NULL
    AND COALESCE((SELECT enabled FROM public.career_studio_rollout_config WHERE id = TRUE), FALSE)
    AND EXISTS (
      SELECT 1 FROM public.career_studio_rollout_users
      WHERE user_id = p_user_id AND enabled = TRUE
    );
$$;

REVOKE ALL ON FUNCTION public.career_studio_access_allowed(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.career_studio_access_allowed(UUID) TO anon, authenticated;
REVOKE ALL ON FUNCTION public.career_studio_service_access_allowed(UUID) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.career_studio_service_access_allowed(UUID) TO service_role;

-- Admin-only mutation functions. The API's existing requireAdmin gate is the
-- authorization boundary; these functions are callable only by service_role
-- and write metadata-only audit records.
CREATE OR REPLACE FUNCTION public.admin_set_career_studio_rollout_user(
  p_target_user_id UUID,
  p_enabled BOOLEAN,
  p_admin_user_id UUID
)
RETURNS public.career_studio_rollout_users
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  rollout_row public.career_studio_rollout_users;
BEGIN
  IF p_target_user_id IS NULL OR p_admin_user_id IS NULL THEN
    RAISE EXCEPTION 'Rollout user and admin user are required';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE id = p_target_user_id) THEN
    RAISE EXCEPTION 'Rollout target user not found';
  END IF;

  INSERT INTO public.career_studio_rollout_users (user_id, enabled, enabled_by)
  VALUES (p_target_user_id, p_enabled, p_admin_user_id)
  ON CONFLICT (user_id) DO UPDATE
    SET enabled = EXCLUDED.enabled, enabled_by = EXCLUDED.enabled_by;

  SELECT * INTO rollout_row
  FROM public.career_studio_rollout_users
  WHERE user_id = p_target_user_id;

  INSERT INTO public.career_studio_rollout_audit_log
    (admin_user_id, target_user_id, action, enabled, result, metadata_json)
  VALUES
    (p_admin_user_id, p_target_user_id, 'rollout_user_updated', p_enabled, 'success',
     jsonb_build_object('scope', 'career_studio', 'operation', CASE WHEN p_enabled THEN 'enable' ELSE 'disable' END));

  RETURN rollout_row;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_set_career_studio_master_switch(
  p_enabled BOOLEAN,
  p_admin_user_id UUID
)
RETURNS public.career_studio_rollout_config
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  config_row public.career_studio_rollout_config;
BEGIN
  IF p_admin_user_id IS NULL THEN
    RAISE EXCEPTION 'Admin user is required';
  END IF;

  UPDATE public.career_studio_rollout_config
  SET enabled = p_enabled, updated_at = NOW(), updated_by = p_admin_user_id
  WHERE id = TRUE
  RETURNING * INTO config_row;

  IF config_row IS NULL THEN
    RAISE EXCEPTION 'Career Studio rollout config not found';
  END IF;

  INSERT INTO public.career_studio_rollout_audit_log
    (admin_user_id, action, enabled, result, metadata_json)
  VALUES
    (p_admin_user_id, 'master_switch_updated', p_enabled, 'success',
     jsonb_build_object('scope', 'career_studio', 'operation', 'master_switch'));

  RETURN config_row;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_set_career_studio_rollout_user(UUID, BOOLEAN, UUID) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.admin_set_career_studio_master_switch(BOOLEAN, UUID) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_career_studio_rollout_user(UUID, BOOLEAN, UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_set_career_studio_master_switch(BOOLEAN, UUID) TO service_role;

-- Replace Career Studio policies with owner + rollout checks. No Portfolio
-- table or legacy Portfolio policy is modified here.
DROP POLICY IF EXISTS "Users can manage own career profiles" ON public.career_profiles;
CREATE POLICY "Users can manage own career profiles" ON public.career_profiles
  FOR ALL USING (auth.uid() = owner_user_id AND public.career_studio_access_allowed(owner_user_id))
  WITH CHECK (auth.uid() = owner_user_id AND public.career_studio_access_allowed(owner_user_id));

DROP POLICY IF EXISTS "Users can manage own career documents" ON public.career_documents;
CREATE POLICY "Users can manage own career documents" ON public.career_documents
  FOR ALL USING (auth.uid() = owner_user_id AND public.career_studio_access_allowed(owner_user_id))
  WITH CHECK (auth.uid() = owner_user_id AND public.career_studio_access_allowed(owner_user_id));

DROP POLICY IF EXISTS "Users can view own CV export events" ON public.cv_export_events;
CREATE POLICY "Users can view own CV export events" ON public.cv_export_events
  FOR SELECT USING (auth.uid() = owner_user_id AND public.career_studio_access_allowed(owner_user_id));

-- Targeted variants remain service-role/API-only, but any future authenticated
-- grant is still protected by the same owner + rollout predicate.
DROP POLICY IF EXISTS "Users can manage own targeted CV variants" ON public.career_targeted_variants;
CREATE POLICY "Users can manage own targeted CV variants" ON public.career_targeted_variants
  FOR ALL USING (auth.uid() = owner_user_id AND public.career_studio_access_allowed(owner_user_id))
  WITH CHECK (auth.uid() = owner_user_id AND public.career_studio_access_allowed(owner_user_id));
